project:
  type: website
  output-dir: _site

website:
  # title: "Personal Website"
  navbar:
    left:
      - href: index.qmd
      - href: resume.qmd

format:
  html:
    theme: ember.scss
    css: styles.css
    toc: true

editor: visual

