project:
  type: website
  output-dir: docs

website:
  # title: "Personal Website"
  twitter-card:
    creator: "@DRNield"
    site: "@DRNield"
  open-graph:
    locale: en_US
  google-analytics: "G-EZ5WZFDWDZ"
  navbar:
    left:
      - href: index.qmd
      - text: Resume
        href: files/resume.pdf

format:
  html:
    theme: ember.scss
    css: styles.css
    toc: true

editor: visual

